### ISSUE TITLE
You do not have enough permissions to access this page.

### ISSUE THREAD

**Issue by UnderlineWords** [atorscho/backend#2]
I get an error message when i create a new tag / category (or custom taxonomy).
"You do not have enough permissions to access this page."
By the way, thanks for your great package.

**Comment by atorscho** [comment]
Oh, that's because in `TaxonomyController` constructor, there was `admin.perm:createTaxonomy` instead of `admin.perm:createTaxonomies`. Now it should work. And thanks for noticing that!

Thanks again, I am glad to know that people find it useful.

**Comment by UnderlineWords** [comment]
Ok It's works fine now :) 
And also i changed line number 43 to "<code>admin.perm:editTaxonomies</code>" in <code>TaxonomyController</code>.
Thanks for your quick response.

**Comment by atorscho** [comment]
Great! And your welcome! :)
